# Generated by Django 3.2.17 on 2023-02-10 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0002_auto_20230210_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_stuff', models.CharField(choices=[('CU', 'current employee'), ('VA', 'vacation'), ('SI', 'sick leave'), ('DI', 'dismissed'), ('ST', 'student')], default='ST', max_length=2)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'мастер',
                'verbose_name_plural': 'мастера',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'профессия',
                'verbose_name_plural': 'профессии',
            },
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_dok', models.CharField(blank=True, max_length=100)),
                ('who_issued', models.TextField(blank=True)),
                ('date_issued', models.DateField(blank=True)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterapp.master')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
            },
        ),
        migrations.CreateModel(
            name='CompletedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterapp.master')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.service')),
            ],
            options={
                'verbose_name': 'выполненая работа',
                'verbose_name_plural': 'выполненые работы',
            },
        ),
    ]
