# Generated by Django 3.2.17 on 2023-02-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedwork',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='completedwork',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dokument',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='master',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='master',
            name='date_start_work',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
