# Generated by Django 3.2.17 on 2023-02-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='master_profissions',
            field=models.ManyToManyField(to='masterapp.Profession'),
        ),
    ]
