# Generated by Django 3.2.17 on 2023-02-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0002_auto_20230210_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedwork',
            name='photo',
            field=models.ImageField(blank=True, upload_to='complete_works'),
        ),
    ]
