# Generated by Django 3.2.17 on 2023-03-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryservice',
            name='photo',
            field=models.ImageField(blank=True, upload_to='category_service'),
        ),
    ]
