# Generated by Django 3.2.17 on 2023-02-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20230210_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryservice',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
