# Generated by Django 3.2.17 on 2023-02-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserService',
        ),
    ]
