# Generated by Django 3.2.17 on 2023-03-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userservice',
            old_name='date',
            new_name='date_service',
        ),
        migrations.RenameField(
            model_name='userservice',
            old_name='time',
            new_name='time_service',
        ),
    ]
